---

- local_action:
    module: community.general.mail
    host: '{{ email_host }}'
    port: '{{ email_port }}'
    username: '{{ email_username }}'
    password: '{{ email_password }}'
    to: '{{ email_to }}'
    subject: 'Deploy {{ _deploy_app }}: {{ _deploy_status }}'
    body: TBD
