---

- name: Start app
  ansible.builtin.systemd_service:
    name: '{{ dyn_proxy.service_name }}'
    state: started

- name: Verify ramp up
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: '{{ dyn_proxy.app.port }}'
    delay: 3
    timeout: 20
    connect_timeout: 2
