---

- name: Stop app
  ansible.builtin.systemd_service:
    name: '{{ dyn_proxy.service_name }}'
    state: stopped

- name: Verify shutdown
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: '{{ dyn_proxy.app.port }}'
    delay: 3
    state: drained
