---

- block:
    - ansible.builtin.import_tasks: deploy/checkout.yml
    - ansible.builtin.import_tasks: deploy/package.yml
    - ansible.builtin.import_tasks: deploy/stop.yml
    - ansible.builtin.import_tasks: deploy/copy.yml
    - ansible.builtin.import_tasks: deploy/start.yml
  rescue:
    - name: Set _tasks_failed flag
      ansible.builtin.set_fact:
        _task_failed_message: '
          Task "{{ ansible_failed_task.name }}" failed with:
          <p style="color:red">{{ ansible_failed_result }}</p>'
  always:
    - name: Include email task
      ansible.builtin.include_tasks: roles/_common/tasks/_email.yml
      vars:
        _deploy_app: 'DynProxy'
        _deploy_status:
          '{{ "FAILURE" if _task_failed_message is defined else "SUCCESS" }}'
        _deploy_email_body:
          '{{ _task_failed_message if _task_failed_message is defined else "OK!" }}'
