---

- import_tasks: _setup.yml
- import_tasks: _checkout.yml
  tags: deploy
- import_tasks: _package.yml
  tags: deploy
- import_tasks: _stop.yml
  tags: deploy
- import_tasks: _copy.yml
  tags: deploy
- import_tasks: _run.yml
  tags: deploy
