---

- ansible.builtin.import_tasks: _setup.yml
- ansible.builtin.import_tasks: _checkout.yml
  tags: deploy
- ansible.builtin.import_tasks: _package.yml
  tags: deploy
- ansible.builtin.import_tasks: _stop.yml
  tags: deploy
- ansible.builtin.import_tasks: _copy.yml
  tags: deploy
- ansible.builtin.import_tasks: _run.yml
  tags: deploy
