name: Setup Ansible
description: "What the name says..."

runs:
  using: composite
  steps:
    - name: Install Ansible
      shell: bash
      run: sudo apt update && sudo apt install -y software-properties-common && sudo add-apt-repository -y --update ppa:ansible/ansible && sudo apt install -y ansible
