---

- name: Create systemd service
  ansible.builtin.template:
    src: java.service.j2
    dest: '/etc/systemd/system/{{ java_service_name }}.service'
    owner: root
    group: root
    mode: '0755'

- name: Run daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
