---

- name: Clear local log file
  ansible.builtin.command: 'truncate -s0 {{ local.log_file }}'
  delegate_to: 127.0.0.1
  changed_when: false
  tags: always

- name: Create bin dir for apps
  ansible.builtin.file:
    path: '{{ system.dev.bin_dir }}'
    state: directory
    mode: '0755'

- name: Create log dir for apps
  ansible.builtin.file:
    path: '{{ system.dev.log_dir }}'
    state: directory
    mode: '0755'

- name: Perform dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  notify: Restart server
