---

- block:
    - ansible.builtin.import_tasks: _deploy/checkout.yml
    - ansible.builtin.import_tasks: _deploy/package.yml
    - ansible.builtin.import_tasks: _deploy/stop.yml
    - ansible.builtin.import_tasks: _deploy/copy.yml
    - ansible.builtin.import_tasks: _deploy/start.yml
  rescue:
    - name: Set task failed message
      ansible.builtin.set_fact:
        _task_failed_message: '
          Task "{{ ansible_failed_task.name }}" failed with:
          <p style="color:red">{{ ansible_failed_result }}</p>'
  always:
    - name: Import email task
      ansible.builtin.import_tasks: roles/_common/tasks/_email.yml
      vars:
        _deploy_app: 'DynProxy'
        _deploy_status:
          '{{ "🛑" if _task_failed_message is defined else "✅" }}'
