name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ID_RSA_2OHM }}" > ~/.ssh/id_rsa_2ohm
          chmod 600 ~/.ssh/id_rsa_2ohm
      - name: Setup Vaults
        run: |
          mkdir ~/.vaults
          echo "${{ secrets.VAULTS_MAIN }}" > ~/.vaults/main
      - name: Run playbook
        working-directory: ./ansible
        run: ansible-playbook dyn_proxy.yml --tags deploy --ssh-extra-args "-o StrictHostKeyChecking=no"
