name: Deploy
on:
  push:
    branches: [ main]
  workflow_dispatch:

jobs:
  deply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible
          playbook: dyn_proxy.yml
          key: ${{ secrets.ID_RSA_2OHM }}
          options: |
            --tags deploy
            --ssh-extra-args "-o StrictHostKeyChecking=no"
