name: Deploy
on:
  push:
    branches: [ main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/dyn_proxy.yml
          key: ${{ secrets.SECRET_SSH_KEY }}
          options: |
            --user root
            --inventory ansible/hosts
            --tags deploy
