name: Package
on:
  push:
    branches: [ main]
  workflow_dispatch:

jobs:
  deply:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./
          playbook: ansible/dyn_proxy.yml
          key: ${{ secrets.ID_RSA_2OHM }}
          options: |
            --tags deploy
